[workspace]
members = ["aic-sdk-sys"]

[workspace.dependencies]
aic-sdk-sys = { version = "0.10.1", path = "aic-sdk-sys" }

[package]
categories = ["multimedia::audio"]
description = "ai-coustics Speech Enhancement SDK"
documentation = "https://docs.rs/aic-sdk"
edition = "2024"
exclude = [".github"]
homepage = "https://ai-coustics.com/sdk/"
keywords = ["cancellation", "enhancement", "noise", "speech", "voice"]
license = "Apache-2.0"
name = "aic-sdk"
readme = "README.md"
repository = "https://github.com/ai-coustics/aic-sdk-rs"
version = "0.10.1"

[dependencies]
aic-sdk-sys = { workspace = true }
thiserror = "2.0.17"

[features]
download-lib = ["aic-sdk-sys/download-lib"]

[[example]]
name = "basic_usage"
path = "examples/basic_usage.rs"
