[workspace]
members = ["aic-sdk-sys"]

[workspace.dependencies]
aic-sdk-sys = { version = "0.12.0", path = "aic-sdk-sys" }

[package]
categories = ["multimedia::audio"]
description = "ai-coustics Speech Enhancement SDK"
documentation = "https://docs.rs/aic-sdk"
edition = "2024"
exclude = [".github"]
homepage = "https://ai-coustics.com/sdk/"
keywords = ["cancellation", "enhancement", "noise", "speech", "voice"]
license = "Apache-2.0"
name = "aic-sdk"
readme = "README.md"
repository = "https://github.com/ai-coustics/aic-sdk-rs"
version = "0.12.0"

[dependencies]
aic-sdk-sys = { workspace = true }
reqwest = { version = "0.12.9", default-features = false, features = ["blocking", "json", "rustls-tls"], optional = true }
serde = { version = "1.0.215", features = ["derive"], optional = true }
serde_json = { version = "1.0.133", optional = true }
sha2 = { version = "0.10.8", optional = true }
thiserror = "2.0.17"

[features]
download-lib = ["aic-sdk-sys/download-lib"]
download-model = ["reqwest", "serde", "serde_json", "sha2"]

[[example]]
name = "basic_usage"
path = "examples/basic_usage.rs"
