[package]
edition = "2024"
name = "build-time-download"
publish = false
version = "0.1.0"

[dependencies]
aic-sdk = { path = "../..", features = ["download-lib"] }

[build-dependencies]
aic-sdk = { path = "../..", features = ["download-lib", "download-model"] }
