[package]
name = "build_time_download"
version = "0.1.0"
edition = "2024"

[dependencies]
aic-sdk = { path = "../..", features = ["download-lib"] }

[build-dependencies]
aic-sdk = { path = "../..", features = ["download-lib", "download-model"] }
